import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { getCleverData, getCleverToken, getSchoolData } from "~/utils/clever";

import Button from "~/components/Button";

const Home: NextPage = () => {  

  const [token, setToken] = useState<string | null>(null);

  return (
    <>
      <Head>
        <title>CoTeacher Environment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-6xl font-bold text-white">CoTeacher Environment</h1>
    
       <button className="text-white outline p-2 rounded m-4" onClick={ getCleverToken } >Get Token</button>
       <button className="text-white outline p-2 rounded m-4" onClick={ getSchoolData } >Get Schools</button>
       <button className="text-white outline p-2 rounded m-4" onClick={ getCleverData } >Get Data</button>
      </main>
    </>
  );
};

export default Home;

